import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  /**
   * Subdomínio futuro (Fatia 2). Null até o admin definir.
   * Único quando preenchido — ver migration 042.
   */
  slug: string | null;
  /** URL pública do logotipo (bucket account-branding). */
  logo_url: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  avatar_url?: string;
  /** Dados pessoais / documento (migration 037) */
  cpf?: string | null;
  data_nascimento?: string | null;
  status?: string | null;
  endereco?: string | null;
  numero?: string | null;
  bairro?: string | null;
  cidade?: string | null;
  estado?: string | null;
  complemento?: string | null;
  cep?: string | null;
  possui_cha?: boolean | null;
  numero_cha?: string | null;
  categoria_cha?: string | null;
  vencimento_cha?: string | null;
  doc_numero?: string | null;
  doc_orgao_emissor?: string | null;
  doc_data_emissao?: string | null;
  profissao?: string | null;
  genero?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

/** WhatsApp transport for an account — exclusive: Meta OR Z-API. */
export type WhatsAppProvider = 'meta' | 'zapi';

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  /** Account tenancy key (one config row per account). */
  account_id?: string;
  /**
   * Active provider for this account. Defaults to `meta` for rows
   * created before multi-provider support.
   */
  provider: WhatsAppProvider;
  /** Meta Cloud API phone number id — required when provider = meta. */
  phone_number_id?: string;
  waba_id?: string;
  /** Meta access token (encrypted at rest) — required when provider = meta. */
  access_token?: string;
  verify_token?: string;
  /** Z-API instance id — required when provider = zapi. */
  zapi_instance_id?: string;
  /** Z-API instance token (encrypted at rest) — required when provider = zapi. */
  zapi_instance_token?: string;
  /** Z-API account Client-Token (encrypted at rest) — required when provider = zapi. */
  zapi_client_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   * Meta-only.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. Meta-only. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. Meta-only. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /** Built-in contact column: `name` | `email`. Legacy `company` is skipped at runtime. */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  /** ID do process_template (legado: pipeline_id). */
  pipeline_id: string;
  /** ID da process_template_stage (legado: stage_id). */
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Catálogo / estoque / PDV (migration 043)
// ============================================================

export type CatalogItemKind = 'product' | 'service';

export type StockMovementReason =
  | 'sale'
  | 'adjustment_in'
  | 'adjustment_out'
  | 'correction'
  | 'initial'
  | 'sale_refund';

export type PaymentMethod = 'cash' | 'pix' | 'card' | 'other';

export type DiscountType = 'none' | 'fixed' | 'percent';

export type SaleStatus = 'confirmed' | 'partially_refunded' | 'cancelled';

export interface CatalogItem {
  id: string;
  account_id: string;
  kind: CatalogItemKind;
  name: string;
  description?: string | null;
  sku?: string | null;
  unit_price: number;
  stock_qty: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface StockMovement {
  id: string;
  account_id: string;
  catalog_item_id: string;
  qty: number;
  reason: StockMovementReason;
  note?: string | null;
  sale_id?: string | null;
  refund_id?: string | null;
  created_by: string;
  created_at: string;
}

export interface Sale {
  id: string;
  account_id: string;
  /** Número sequencial na conta (texto do inteiro; UI usa formatSaleCode). */
  code: string;
  status: SaleStatus;
  contact_id?: string | null;
  payment_method: PaymentMethod;
  subtotal: number;
  discount_type: DiscountType;
  discount_value: number;
  discount_amount: number;
  total: number;
  sold_by: string;
  created_at: string;
  items?: SaleItem[];
  refunds?: SaleRefund[];
  contact?: Contact | null;
}

export interface SaleItem {
  id: string;
  sale_id: string;
  catalog_item_id: string;
  kind: CatalogItemKind;
  name: string;
  unit_price: number;
  qty: number;
  line_total: number;
  /** Preenchido no GET detalhe / UI de estorno. */
  qty_refunded?: number;
  qty_remaining?: number;
}

export interface SaleRefund {
  id: string;
  account_id: string;
  sale_id: string;
  refunded_by: string;
  note?: string | null;
  subtotal_refunded: number;
  discount_refunded: number;
  total_refunded: number;
  created_at: string;
  items?: SaleRefundItem[];
}

export interface SaleRefundItem {
  id: string;
  refund_id: string;
  sale_item_id: string;
  catalog_item_id: string;
  qty: number;
  unit_price: number;
  line_total: number;
}

// ============================================================
// Locais de aula (migration 047)
// ============================================================

export type ClassLocationStatus = "active" | "inactive";

export type ClassLocationCostType =
  | "monthly_fee"
  | "per_class"
  | "per_day"
  | "per_student";

export interface ClassLocation {
  id: string;
  account_id: string;
  name: string;
  endereco?: string | null;
  numero?: string | null;
  complemento?: string | null;
  bairro?: string | null;
  cidade?: string | null;
  estado?: string | null;
  cep?: string | null;
  status: ClassLocationStatus;
  has_expense: boolean;
  expense_type?: ClassLocationCostType | null;
  expense_amount?: number | null;
  /** OM/STA do local (catálogo maritime_authorities). */
  authority_id?: number | null;
  created_at: string;
  updated_at: string;
  bonus_rules?: ClassLocationBonusRule[];
}

export interface ClassLocationBonusRule {
  id: string;
  account_id: string;
  location_id: string;
  bonus_type: ClassLocationCostType;
  bonus_amount: number;
  starts_on: string;
  ends_on?: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Equipamentos / frota (migration 048)
// ============================================================

export type EquipmentKind = "vehicle" | "vessel";
export type EquipmentSubtype = "car" | "motorcycle" | "jet_ski" | "boat";
export type EngineCycle = "2t" | "4t";
export type EquipmentFuel =
  | "gasoline"
  | "ethanol"
  | "flex"
  | "diesel"
  | "electric";
export type MeterUnit = "km" | "hours";
export type EquipmentStatus =
  | "active"
  | "in_maintenance"
  | "inactive"
  | "decommissioned";
export type MaintenanceKind = "preventive" | "corrective";
export type MaintenanceStatus =
  | "scheduled"
  | "in_progress"
  | "completed"
  | "cancelled";

export interface Equipment {
  id: string;
  account_id: string;
  name: string;
  kind: EquipmentKind;
  subtype: EquipmentSubtype;
  brand: string;
  model: string;
  engine_cycle?: EngineCycle | null;
  fuel: EquipmentFuel;
  meter_value: number;
  meter_unit: MeterUnit;
  document_expires_on: string;
  plate_or_registration: string;
  dpem_expires_on?: string | null;
  dpem_protocol?: string | null;
  status: EquipmentStatus;
  created_at: string;
  updated_at: string;
  maintenances?: EquipmentMaintenance[];
  /** Preenchido na listagem: próxima next_due_on ativa. */
  next_maintenance_due_on?: string | null;
}

export interface EquipmentMaintenance {
  id: string;
  account_id: string;
  equipment_id: string;
  kind: MaintenanceKind;
  performed_on: string;
  description: string;
  meter_value_at?: number | null;
  cost?: number | null;
  vendor?: string | null;
  next_due_on?: string | null;
  status: MaintenanceStatus;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Instrutores (migration 051)
// ============================================================

export type ChaCategory =
  | "mta"
  | "ara"
  | "mtr"
  | "cpa"
  | "mta_ara"
  | "mta_mtr"
  | "mta_cpa";

export type InstructorStatus = "active" | "inactive";

export interface Instructor {
  id: string;
  account_id: string;
  user_id?: string | null;
  full_name: string;
  phone: string;
  birth_date: string;
  cha_number: string;
  cha_category: ChaCategory;
  cha_expires_on: string;
  status: InstructorStatus;
  pix_key: string;
  created_at: string;
  updated_at: string;
  locations?: InstructorLocation[];
  weekly?: InstructorWeeklyAvailability[];
  unavailability?: InstructorUnavailability[];
  /** Preenchido na listagem admin. */
  locations_count?: number;
}

export interface InstructorLocation {
  id: string;
  account_id: string;
  instructor_id: string;
  location_id: string;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface InstructorWeeklyAvailability {
  id: string;
  account_id: string;
  instructor_id: string;
  /** 0=domingo … 6=sábado */
  weekday: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface InstructorUnavailability {
  id: string;
  account_id: string;
  instructor_id: string;
  on_date: string;
  reason?: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Processos / enrollment (migration 054)
// ============================================================

export type {
  ProcessStatus,
  AdvanceMode,
  CommercialStatus,
  ProcessDomainEventType,
  ProcessTemplate,
  ProcessTemplateStage,
  EnrollmentProcess,
  ProcessStageHistory,
  ProcessTemplateStageInput,
  ProcessFieldType,
  ProcessTemplateStageField,
  ProcessFieldValueRow,
  ProcessFieldsSummary,
  ProcessTemplateStageFieldInput,
} from "@/lib/processes/types";

export type {
  ProcessClassStatus,
  ProcessClass,
  ProcessClassEnrollment,
} from "@/lib/classes/types";

export type {
  AgendaEventKind,
  AgendaEventStatus,
  AgendaColorKey,
  AgendaAssignee,
  AgendaEvent,
} from "@/lib/agenda/types";
